package champions;

public enum Synergies_SET2 {
    ALCHEMIST,ASSASSIN, AVATAR, BERSERKER, BLADEMASTER, CLOUD, CRYSTAL, DESERT, DRUID, ELECTRIC,GLACIAL, INFERNO,
    LIGHT, MAGE, MOUNTAIN, MYSTIC, OCEAN, POISON, PREDATOR, RANGER, SHADOW, STEEL, SUMMONER, WARDEN, WOODLAND
}
